import uuid
import uuid6
import datetime
from sqlalchemy import Uuid, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.session import Base

class UserFace(Base):
    """SQLAlchemy model storing eKYC face biometric metadata linked to user accounts.
    
    Attributes:
        id (uuid.UUID): Primary key, unique identifier of this face record (UUIDv7).
        user_id (uuid.UUID): Foreign key referencing the users table.
        face_id (uuid.UUID): Unique face ID generated by the FAISS model registering.
        created_at (datetime.datetime): Timestamp when the face was registered.
    """
    __tablename__ = "user_faces"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid6.uuid7)
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, 
        ForeignKey("users.id", ondelete="CASCADE"), 
        nullable=False, 
        unique=True
    )
    face_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, unique=True)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    # Bi-directional relationship with User model
    user: Mapped["User"] = relationship("User", back_populates="face")
