from enum import Enum

class ErrorCode(str, Enum):
    """Application Error Codes (Uppercase string constants)."""
    ALREADY_CHECKIN = "ALREADY_CHECKIN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    FACE_NOT_REGISTERED = "FACE_NOT_REGISTERED"
    FACE_ALREADY_REGISTERED = "FACE_ALREADY_REGISTERED"
    DUPLICATE_FACE_DETECTED = "DUPLICATE_FACE_DETECTED"
    SPOOFING_ATTACK_DETECTED = "SPOOFING_ATTACK_DETECTED"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    INVALID_FRAME_COUNT = "INVALID_FRAME_COUNT"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_SYSTEM_ERROR = "INTERNAL_SYSTEM_ERROR"
    NO_FACE_DETECTED = "NO_FACE_DETECTED"
    WRONG_FACE = "WRONG_FACE"
